[world]
name = "Quick Draw Arena"
description = "A 1v1 commit-reveal dueling game with rock-paper-scissors style combat"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/quick-draw-arena"
seed = "quick_draw_arena"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/quick-draw-arena"
telegram = "https://t.me/dojoengine"

[namespace]
default = "quick_draw_arena"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"quick_draw_arena" = ["quick_draw_arena-actions"]

# local katana testnet deplo
# world = 0x0334b5b21b21e43bc45661f1bb915cfa96676e731aac509200d9d789a80d94a4
